version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: cd client && npm install
      - run:
          name: Run Tests
          command: cd client && npm test

  sonarqube_scan:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    steps:
      - checkout
      - run:
          name: Run SonarQube Scanner
          command: |
            sonar-scanner \
              -Dsonar.projectKey=TehrinReddy_apds7311-poe-TehrinReddy \
              -Dsonar.organization=tehrinreddy \
              -Dsonar.sources=client \
              -Dsonar.host.url=${SONAR_HOST_URL} \
              -Dsonar.login=${SONAR_TOKEN}

workflows:
  version: 2
  build_and_scan:
    jobs:
      - build
      - sonarqube_scan:
          requires:
            - build
