version: 2.1

executors:
  dotnet-executor:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0  # Use .NET 8.0 SDK image
    working_directory: ~/repo

jobs:
  sonar_scan:
    executor: dotnet-executor
    steps:
      - checkout  # Ensure we pull the latest code
      - run:
          name: Install Node.js
          command: |
            curl -sL https://deb.nodesource.com/setup_18.x | bash -
            apt-get install -y nodejs
      - run:
          name: Install Dependencies
          command: dotnet restore CustomerPortalAPI.Server/CustomerPortalAPI.Server.csproj  # Specify the project file
      - run:
          name: Build Project
          command: dotnet build CustomerPortalAPI.Server/CustomerPortalAPI.Server.csproj  # Specify the project file
      - run:
          name: Install SonarScanner for .NET
          command: dotnet tool install --global dotnet-sonarscanner
            
 

workflows:
  version: 2
  sonar_workflow:
    jobs:
      - sonar_scan

